name: Melonx_release

on:
  workflow_dispatch:
    inputs:
      release__nightly:
        description: Create a release
        type: boolean
        required: false

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-15

    env:
      scheme: MeloNX
      archive_path: archive

    outputs:
      scheme: ${{ steps.scheme.outputs.scheme }}
      archive_path: ${{ env.archive_path }}

    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.409'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup dotnet symlink
        run: |
          sudo mkdir -p /usr/local/share/dotnet
          sudo ln -sf /Users/runner/.dotnet/dotnet /usr/local/share/dotnet/dotnet

      - name: First archive attempt
        continue-on-error: true
        run: |
          cd src/MeloNX/

          xcodebuild archive \
            -archivePath "../../MeloNX_archive" \
            -scheme "MeloNX.app" \
            -target "MeloNX" \
            -sdk iphoneos \
            -arch arm64 \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Configure project through Ruby script
        run: |
          gem install xcodeproj
          ruby embed_sign_dylib.rb

      - name: Build MeloNX archive
        run: |
          cd src/MeloNX/

          set -o pipefail

          xcodebuild archive \
            -archivePath "../../MeloNX_archive" \
            -scheme "MeloNX" \
            -target "MeloNX" \
            -sdk iphoneos \
            -arch arm64 \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: List created files
        run: |
          pwd
          ls -la

      - name: Compress build artifact
        run: |
          tar -cvf "MeloNX_archive.xcarchive.tar" "MeloNX_archive.xcarchive"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeloNX_archive.xcarchive.tar
          path: MeloNX_archive.xcarchive.tar

  package:
    name: Create fake-signed IPA package
    runs-on: ubuntu-latest
    needs: build

    env:
      scheme: MeloNX
      archive_path: MeloNX_archive.xcarchive.tar

    outputs:
      artifact: MeloNX_beta.ipa

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: MeloNX_archive.xcarchive.tar

      - name: Extract build artifact
        run: |
          tar -xf "MeloNX_archive.xcarchive.tar"

      - name: Install ldid
        run: |
          curl -sSL \
            -o /usr/local/bin/ldid \
            "${{ github.server_url }}/ProcursusTeam/ldid/releases/latest/download/ldid_linux_$(uname -m)"

          chmod +x /usr/local/bin/ldid

      - name: Fake sign frameworks and MeloNX
        run: |
          find "MeloNX_archive.xcarchive/Products/Applications/MeloNX.app" \
            -type d \
            -path '*/Frameworks/*.framework' \
            -exec ldid -SMeloNX-hv.entitlements {} \;

          ldid \
            -SMeloNX-hv.entitlements \
            "MeloNX_archive.xcarchive/Products/Applications/${scheme}.app"

      - name: Create IPA
        run: |
          mv "MeloNX_archive.xcarchive/Products/Applications" Payload

          zip -r "MeloNX.ipa" "Payload" \
            -x "._*" \
            -x ".DS_Store" \
            -x "__MACOSX/*"

      - name: Upload MeloNX IPA
        uses: actions/upload-artifact@v4
        with:
          name: MeloNX_beta.ipa
          path: MeloNX.ipa
